QUERY_TYPE_NAMES = {1 : 'A', 2: 'NS', 5: 'CNAME', 15 : 'MX', 28: 'AAAA'}
OPCODES = { 0 : 'QUERY', 1 : 'IQUERY', 2 : 'STATUS'}
QUERY_CLASS_NAMES = {1  : 'IN'}
MESSAGE_TYPES = {0 : 'QUERY', 1 : 'RESPONSE'}
RESPONSE_CODE_NAMES = {0 : 'NO ERROR', 1 : 'FORMAT_ERROR', 2 : 'SERVER FAILURE', 3 : 'NAME ERROR', 4 : 'NOT IMPLEMENTED', 5: 'REFUSED'}
